FROM quay.io/centos-bootc/centos-bootc:stream10

RUN dnf -y install cloud-init && \
    ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

#COPY usr/ usr/

# Bind the httpd container image
#RUN ln -sr /usr/share/containers/systemd/httpd.container /usr/lib/bootc/bound-images.d/
